# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kail < Formula
  desc "kubernetes tail - pod log viewer"
  homepage "https://github.com/boz/kail"
  version "0.16.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/boz/kail/releases/download/v0.16.1/kail_v0.16.1_darwin_arm64.tar.gz"
      sha256 "53bd81efe1c85d51d3688d7b0575fba458d75954895ca50d211ff31e5ca9f5a0"

      def install
        bin.install "kail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/boz/kail/releases/download/v0.16.1/kail_v0.16.1_darwin_amd64v2.tar.gz"
      sha256 "ae27bdcdeaa665dc8eec4cf7a43e5b7626ed6b1a3b731af7200a39b71a8a3702"

      def install
        bin.install "kail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/boz/kail/releases/download/v0.16.1/kail_v0.16.1_linux_arm64.tar.gz"
      sha256 "94cb35d36df996dacc4b97de24fa3513674c73e6b46fb92f9ebdb7d0271a76f1"

      def install
        bin.install "kail"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/boz/kail/releases/download/v0.16.1/kail_v0.16.1_linux_amd64v2.tar.gz"
      sha256 "0f71b59b7eb9df05694e0e3ada17609f9d6276cbc4de197df3e200c9cab47842"

      def install
        bin.install "kail"
      end
    end
  end
end
