# This file was generated by GoReleaser. DO NOT EDIT.
class Kail < Formula
  desc "kubernetes tail - pod log viewer"
  homepage "https://github.com/boz/kail"
  url "https://github.com/boz/kail/releases/download/v0.10.0/kail_0.10.0_darwin_amd64.tar.gz"
  version "0.10.0"
  sha256 "eb68816ae5e3fb77593649b1c698b3012f3eff415df51b41c8595e3ba4f5d78a"

  def install
    bin.install "kail"
  end
end
